global:
  scrape_interval:     15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
scrape_configs:
  - job_name: coin
    scrape_interval: 1m
    scrape_timeout: 15s
    metrics_path: /coin
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']
  - job_name: predict-linear
    scrape_interval: 1m
    scrape_timeout: 45s
    metrics_path: /linear
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']
  - job_name: predict-arima
    scrape_interval: 1m
    scrape_timeout: 60s
    metrics_path: /arima
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']
  - job_name: predict-lstm-btc
    scrape_interval: 2m
    scrape_timeout: 2m
    metrics_path: /lstm
    params:
      target: ['btc_usd']
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']
  - job_name: predict-lstm-eth
    scrape_interval: 2m
    scrape_timeout: 2m
    metrics_path: /lstm
    params:
      target: ['eth_usd']
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']
  - job_name: predict-lstm-bch
    scrape_interval: 2m
    scrape_timeout: 2m
    metrics_path: /lstm
    params:
      target: ['bch_usd']
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']
  - job_name: predict-sidecar
    scrape_interval: 1m
    scrape_timeout: 60s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ['104.154.136.152:8077']