global:
  scrape_interval:     15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
scrape_configs:
  - job_name: coin
    scrape_interval: 1m
    scrape_timeout: 15s
    metrics_path: /coin
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']
  - job_name: predict-linear
    scrape_interval: 1m
    scrape_timeout: 45s
    metrics_path: /linear
    scheme: http
    static_configs:
    - targets: ['us-central1-starry-tracker-215615.cloudfunctions.net']